
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Dec 05 19:54:32 IST 2012
//----------------------------------------------------

package org.tamedragon.compilers.clang.abssyntree;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SHORT = 22;
  public static final int BITWISE_XOR = 64;
  public static final int SIGNED = 23;
  public static final int IDENTIFIER = 80;
  public static final int GT = 59;
  public static final int CONST = 6;
  public static final int ASM = 34;
  public static final int ONES_COMPLEMENT = 47;
  public static final int REGISTER = 20;
  public static final int BITWISE_OR = 65;
  public static final int ENUM = 12;
  public static final int RBRACK = 44;
  public static final int SIZEOF = 24;
  public static final int COMMA = 39;
  public static final int RBRACE = 36;
  public static final int LEFT_SHIFT_ASSIGN = 78;
  public static final int RPAREN = 42;
  public static final int LBRACK = 43;
  public static final int LEFT_SHIFT = 56;
  public static final int LT = 58;
  public static final int INCREMENT = 48;
  public static final int DOUBLE = 10;
  public static final int STRUCT = 26;
  public static final int LBRACE = 35;
  public static final int LPAREN = 41;
  public static final int INTEGER_LITERAL = 84;
  public static final int NOT = 46;
  public static final int FLOAT = 14;
  public static final int GOTO = 16;
  public static final int BITWISE_OR_ASSIGN = 77;
  public static final int MODULO = 55;
  public static final int ADD_ASSIGN = 70;
  public static final int LONG = 19;
  public static final int PLUS = 50;
  public static final int DIVIDE = 54;
  public static final int QUESTION = 68;
  public static final int NOT_EQUALS = 63;
  public static final int WHILE = 33;
  public static final int UNION = 29;
  public static final int ASSIGN = 69;
  public static final int CHAR = 5;
  public static final int SWITCH = 27;
  public static final int DO = 9;
  public static final int FOR = 15;
  public static final int STAR = 52;
  public static final int MINUS_ASSIGN = 71;
  public static final int VOID = 31;
  public static final int EXTERN = 13;
  public static final int RETURN = 21;
  public static final int MODULO_ASSIGN = 74;
  public static final int ELSE = 11;
  public static final int BREAK = 3;
  public static final int DOT = 38;
  public static final int INT = 18;
  public static final int LTE = 60;
  public static final int MULTIPLY_ASSIGN = 72;
  public static final int STRING_LITERAL = 82;
  public static final int EOF = 0;
  public static final int SEMICOLON = 40;
  public static final int POINTER_MEM_ACCESS = 45;
  public static final int DEFAULT = 8;
  public static final int DECREMENT = 49;
  public static final int DIVIDE_ASSIGN = 73;
  public static final int MINUS = 51;
  public static final int BITWISE_AND_ASSIGN = 75;
  public static final int OR = 67;
  public static final int error = 1;
  public static final int GTE = 61;
  public static final int CONTINUE = 7;
  public static final int IF = 17;
  public static final int UNSIGNED = 30;
  public static final int COLON = 37;
  public static final int RIGHT_SHIFT = 57;
  public static final int CHAR_LITERAL = 81;
  public static final int VOLATILE = 32;
  public static final int CASE = 4;
  public static final int RIGHT_SHIFT_ASSIGN = 79;
  public static final int BITWISE_XOR_ASSIGN = 76;
  public static final int AND = 66;
  public static final int STATIC = 25;
  public static final int BITWISE_AND = 53;
  public static final int TYPEDEF = 28;
  public static final int AUTO = 2;
  public static final int EQUALS = 62;
  public static final int FLOATING_POINT_LITERAL = 83;
}

